# Base image
FROM node:20

# App directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Prisma generate
RUN npx prisma generate

# Expose backend port
EXPOSE 5000

# Start app
CMD ["npm", "run", "dev"]